#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Podaj jako parametr plik wejsciowyi!";
	exit;
fi;

if [ ! -f $1 ]; then
	echo "Podany plik nie istnieje!";
	exit;
fi;


dane=`cat $1 | tr -s ' ' '\t' | cut -f1 | uniq`

for i in $dane
do

tmp=s;

# 	echo $i
# // (small - `hget rat99`) / (`hget $tmp`) * 100;
awk "BEGIN	{ test = 10000000000; czas = -1.0; iter = 0; look = 0; min = 0; max = 10000000000000000000000000; count = 0;

	split(\"a280 berlin52 bier127 eil51 eil76 eil101 gil262 kroA100 kroB100 kroC100 kroD100 kroE100 kroA150 kroB150 kroA200 kroB200 lin105 lin318 linhp318 pr76 pr107 pr124 pr136 pr144 pr152 pr226 pr264 pr299 pr439 rat99 rat575 rat783\", a);
	split(\"2579 7542 118282 426 538 629 2378 21282 22141 20749 21294 22068 26524 26130 29368 29437 14379 42029 41345 108159 44303 59030 96772 58537 73682 80369 49135 48191 107217 1211 6773 8806\", b);
	for(i=1;i in a;i++){c[a[i]]=b[i]};

}
\$1 == \"$i\"	{ 
			if ( \$5 < max && czas <= \$2) {
				max = \$5;
				nazwa = \$1;
				czas = \$2;
				iter = \$4;
				look = \$5;
			} else {
				wyniki[count] = max;
				czasy[count++] = czas;
				max = 10000000000000000000000000;
				czas = -1.0;
				iter = 0;
				look = 0;
			}
		}
	END { 
		avg = 0;
		for (i in wyniki)
			avg += wyniki[i];
		avg_czas = 0;
		for (i in czasy) {
			avg_czas += czasy[i];
		}
		avg /= (count);
		match(nazwa, /([a-zA-Z0-9]*).*/, arr);
		avg_p = (avg - c[arr[1]]) / c[arr[1]] * 100 ; 
		avg_czas /= (count);	
		ef = (avg_p * avg_czas);
		print nazwa \"\t\" avg_p \"\t\" avg_czas \"\t\" ef
	
	}" $1
done
